sudo: false

os:
  - linux

language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - php --version
  - composer --version
  - composer self-update

install:
  - composer install -vvv

script:
  - php vendor/bin/phpunit -c phpunit.xml tests/Unit/AppObjectTest.php
